### ISSUE TITLE
EAN-13 number of product combination is not passed to API in PrestaShop module

### ISSUE THREAD

**Issue by muyncky** [dropday-io/PrestaShop#17]
#### Describe the bug

**In the PrestaShop module.**

The ean13 number that belongs to the product combination is not sent to the API, instead the product ean13 is sent.

---
#### Expected behavior

If available, sent the product combination ean13, if not pass the product ean13.

---
#### Steps to Reproduce

1. Create a product with a combinaton.
2. Add an ean13 to the product, and a different ean13 in the product combination
3. Place an order of that product combination
4. You will see that an order is placed in Dropday with the ean of the product

**Comment by dropday-io** [comment]
This is tested, and not an issue.
